GET ALL POSTS
###
GET http://localhost:3000/posts/

CREATE A POST 
###
POST http://localhost:3000/posts/
Content-Type: application/json 

{
  'title': 'Ravis Adventure',
  "description": "Ravi explores the vibrant culture of Chennai.",
  "userId": 2,
  "images": "girish1.jpg,girish2.jpg"
}

UPDATA A POST 
###
PUT http://localhost:3000/posts/
Content-Type: application/json 

{
  'title': 'Ravis Adventure',
  "description": "Ravi explores the vibrant culture of Chennai.",
  "userId": 3,
  "images": "girish1.jpg,girish2.jpg"
}

DELETE A POST 
###
DELETE http://localhost:3000/posts/3

GET ALL POSTS OF A USER 
###
GET http://localhost:3000/users/2